### ISSUE TITLE
Sparse Conjugate Gradient

### ISSUE THREAD

**Issue by KristofferC** [ranjanan/GPU-benchmarking#1]
Hi,

If you are interested, I have some code here: https://github.com/KristofferC/exploration/blob/master/gpufem/gpusolve.jl that does a sparse conjugate gradient with incomplete cholesky / jacobi / no preconditioner. It uses a method I added for cuSPARSE here: https://github.com/JuliaGPU/CUSPARSE.jl/pull/13

There is also one for CPUs which uses the exact same algorithm but with no preconditioner: https://github.com/KristofferC/exploration/blob/master/gpufem/cpusolve.jl

To compare the IC preconditioner performance of CPU vs GPU the IC0 preconditioner in MKL could be used.

Here is a figure of no preconditioner CPU vs GPU (it also compares the time to do a full cholesky which is the fastest one for the benchmarks I did). The labels with 32 is using Float32s. The time is to reach the same tolerance as the full Cholesky:

![image](https://cloud.githubusercontent.com/assets/1282691/10560711/bd8c1180-7513-11e5-9f46-457fb072e099.png)

**Comment by ranjanan** [comment]
Thanks for the reference, @KristofferC . Will look into this.
